name: Implementation

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:


  impl_mult_wfifos_slink_35t:
    runs-on: ubuntu-latest
    env:
      Board: 35t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_mult_wfifos_slink.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: mult_wfifos_slink_35t
          path: ./neorv32_mult_wfifos_slink_35t.bit

  impl_mult_wfifos_slink_100t:
    runs-on: ubuntu-latest
    env:
      Board: 100t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_mult_wfifos_slink.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: mult_wfifos_slink_100t
          path: ./neorv32_mult_wfifos_slink_100t.bit

  impl_multp_wfifos_slink_35t:
    runs-on: ubuntu-latest
    env:
      Board: 35t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_multp_wfifos_slink.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: multp_wfifos_slink_35t
          path: ./neorv32_multp_wfifos_slink_35t.bit

  impl_multp_wfifos_slink_100t:
    runs-on: ubuntu-latest
    env:
      Board: 100t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_multp_wfifos_slink.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: multp_wfifos_slink_100t
          path: ./neorv32_multp_wfifos_slink_100t.bit

  impl_multp_slink_35t:
    runs-on: ubuntu-latest
    env:
      Board: 35t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_multp_slink.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: multp_slink_35t
          path: ./neorv32_multp_slink_35t.bit

  impl_multp_slink_100t:
    runs-on: ubuntu-latest
    env:
      Board: 100t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_multp_slink.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: multp_slink_100t
          path: ./neorv32_multp_slink_100t.bit

  impl_mult_wfifos_wishbone_35t:
    runs-on: ubuntu-latest
    env:
      Board: 35t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_mult_wfifos_wishbone.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: mult_wfifos_wishbone_35t
          path: ./neorv32_mult_wfifos_wishbone_35t.bit

  impl_mult_wfifos_wishbone_100t:
    runs-on: ubuntu-latest
    env:
      Board: 100t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_mult_wfifos_wishbone.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: mult_wfifos_wishbone_100t
          path: ./neorv32_mult_wfifos_wishbone_100t.bit

  impl_multp_wfifos_wishbone_35t:
    runs-on: ubuntu-latest
    env:
      Board: 35t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_multp_wfifos_wishbone.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: multp_wfifos_wishbone_35t
          path: ./neorv32_multp_wfifos_wishbone_35t.bit

  impl_multp_wfifos_wishbone_100t:
    runs-on: ubuntu-latest
    env:
      Board: 100t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_multp_wfifos_wishbone.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: multp_wfifos_wishbone_100t
          path: ./neorv32_multp_wfifos_wishbone_100t.bit

