name: Implementation

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types:
      - published

permissions:
  contents: write

jobs:


  impl_mult_wfifos_slink_35t:
    runs-on: ubuntu-latest
    env:
      Board: 35t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_mult_wfifos_slink.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: mult_wfifos_slink_35t
          path: ./neorv32_mult_wfifos_slink_35t.bit

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Practices --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: DEF
          FILES: ./neorv32_mult_wfifos_slink_35t.bit

  impl_mult_wfifos_slink_100t:
    runs-on: ubuntu-latest
    env:
      Board: 100t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_mult_wfifos_slink.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: mult_wfifos_slink_100t
          path: ./neorv32_mult_wfifos_slink_100t.bit

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Practices --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: DEF
          FILES: ./neorv32_mult_wfifos_slink_100t.bit

  impl_multp_wfifos_slink_35t:
    runs-on: ubuntu-latest
    env:
      Board: 35t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_multp_wfifos_slink.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: multp_wfifos_slink_35t
          path: ./neorv32_multp_wfifos_slink_35t.bit

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Practices --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: DEF
          FILES: ./neorv32_multp_wfifos_slink_35t.bit

  impl_multp_wfifos_slink_100t:
    runs-on: ubuntu-latest
    env:
      Board: 100t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_multp_wfifos_slink.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: multp_wfifos_slink_100t
          path: ./neorv32_multp_wfifos_slink_100t.bit

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Practices --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: DEF
          FILES: ./neorv32_multp_wfifos_slink_100t.bit

  impl_multp_slink_35t:
    runs-on: ubuntu-latest
    env:
      Board: 35t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_multp_slink.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: multp_slink_35t
          path: ./neorv32_multp_slink_35t.bit

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Practices --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: DEF
          FILES: ./neorv32_multp_slink_35t.bit

  impl_multp_slink_100t:
    runs-on: ubuntu-latest
    env:
      Board: 100t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_multp_slink.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: multp_slink_100t
          path: ./neorv32_multp_slink_100t.bit

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Practices --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: DEF
          FILES: ./neorv32_multp_slink_100t.bit

  impl_mult_wfifos_wishbone_35t:
    runs-on: ubuntu-latest
    env:
      Board: 35t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_mult_wfifos_wishbone.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: mult_wfifos_wishbone_35t
          path: ./neorv32_mult_wfifos_wishbone_35t.bit

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Practices --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: DEF
          FILES: ./neorv32_mult_wfifos_wishbone_35t.bit

  impl_mult_wfifos_wishbone_100t:
    runs-on: ubuntu-latest
    env:
      Board: 100t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_mult_wfifos_wishbone.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: mult_wfifos_wishbone_100t
          path: ./neorv32_mult_wfifos_wishbone_100t.bit

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Practices --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: DEF
          FILES: ./neorv32_mult_wfifos_wishbone_100t.bit

  impl_multp_wfifos_wishbone_35t:
    runs-on: ubuntu-latest
    env:
      Board: 35t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_multp_wfifos_wishbone.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: multp_wfifos_wishbone_35t
          path: ./neorv32_multp_wfifos_wishbone_35t.bit

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Practices --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: DEF
          FILES: ./neorv32_multp_wfifos_wishbone_35t.bit

  impl_multp_wfifos_wishbone_100t:
    runs-on: ubuntu-latest
    env:
      Board: 100t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_multp_wfifos_wishbone.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: multp_wfifos_wishbone_100t
          path: ./neorv32_multp_wfifos_wishbone_100t.bit

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Practices --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: DEF
          FILES: ./neorv32_multp_wfifos_wishbone_100t.bit

  impl_mults_cfu_35t:
    runs-on: ubuntu-latest
    env:
      Board: 35t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_mults_cfu.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: mults_cfu_35t
          path: ./neorv32_mults_cfu_35t.bit

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Practices --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: DEF
          FILES: ./neorv32_mults_cfu_35t.bit

  impl_mults_cfu_100t:
    runs-on: ubuntu-latest
    env:
      Board: 100t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_mults_cfu.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: mults_cfu_100t
          path: ./neorv32_mults_cfu_100t.bit

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Practices --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: DEF
          FILES: ./neorv32_mults_cfu_100t.bit

  impl_mult_wfifos_cfs_35t:
    runs-on: ubuntu-latest
    env:
      Board: 35t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_mult_wfifos_cfs.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: mult_wfifos_cfs_35t
          path: ./neorv32_mult_wfifos_cfs_35t.bit

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Practices --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: DEF
          FILES: ./neorv32_mult_wfifos_cfs_35t.bit

  impl_mult_wfifos_cfs_100t:
    runs-on: ubuntu-latest
    env:
      Board: 100t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_mult_wfifos_cfs.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: mult_wfifos_cfs_100t
          path: ./neorv32_mult_wfifos_cfs_100t.bit

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Practices --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: DEF
          FILES: ./neorv32_mult_wfifos_cfs_100t.bit

  impl_multp_wfifos_cfs_35t:
    runs-on: ubuntu-latest
    env:
      Board: 35t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_multp_wfifos_cfs.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: multp_wfifos_cfs_35t
          path: ./neorv32_multp_wfifos_cfs_35t.bit

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Practices --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: DEF
          FILES: ./neorv32_multp_wfifos_cfs_35t.bit

  impl_multp_wfifos_cfs_100t:
    runs-on: ubuntu-latest
    env:
      Board: 100t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_multp_wfifos_cfs.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: multp_wfifos_cfs_100t
          path: ./neorv32_multp_wfifos_cfs_100t.bit

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Practices --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: DEF
          FILES: ./neorv32_multp_wfifos_cfs_100t.bit

  impl_multp_cfs_35t:
    runs-on: ubuntu-latest
    env:
      Board: 35t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_multp_cfs.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: multp_cfs_35t
          path: ./neorv32_multp_cfs_35t.bit

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Practices --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: DEF
          FILES: ./neorv32_multp_cfs_35t.bit

  impl_multp_cfs_100t:
    runs-on: ubuntu-latest
    env:
      Board: 100t

    steps:

      - name: '🧰 Checkout'
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: docker://ghcr.io/unike267/containers/impl-arty:latest
        with:
          args: ./impl/nextpnr/impl_multp_cfs.sh
      
      - name: '📤 Upload artifact'
        uses: actions/upload-artifact@v4
        with:
          name: multp_cfs_100t
          path: ./neorv32_multp_cfs_100t.bit

      - name: '📤 Upload Release Assets'
        run: gh release upload --repo Unike267/Practices --clobber $TAG $FILES
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: DEF
          FILES: ./neorv32_multp_cfs_100t.bit

